[versions]
agp = "8.12.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
circularprogressbar = "3.1.0"
cardview = "1.0.0"
retrofit = "3.0.0"
converterGson = "3.0.0"
loggingInterceptor = "5.1.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
circularprogressbar = { group = "com.mikhaellopez", name = "circularprogressbar", version.ref = "circularprogressbar" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converterGson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

